class AmazonPrime{
    static String kannadaMovies[] = {"Ulidavaru kandanthe", "K.g.f", "lucia", "Rangi Taranga", "ugramm", "Godhi banna sadharana mykattu", "upendra", "mungaru male", "kirik party", "jogi", "Bhaktha prahalda", "u turn", "Tagaru", "amrtha varshini", "Rama Rama re","Navagraha","Rama shama bhama", "Gultoo", "googly", "Gaalipata", "pancharangi", "love mocktail", "Kalpana 1", "kalpana 2", "uppi2"};
    static String hindiMovies[] = {"I am kalam", "madaari", "Talvar", "pinjar", "udta Punjab", "veer zaara", "deewaar", "Dear Zindagi", "Garm hava", "maqbool", "lagaan", "Rang De basanthi", "Koshish", "3 Idiots", "sardar udham", "thirst", "Anand", "The chess palyer", "Guide", "dangal", "udaan", "jai Bheem", "Haider", "queen", " guru"};
    static String telguMovies[] = {"Adipurush", "vimanam", "Bichagadu 2", "bhuvana Vijayam", "custody", "Arangetram", "Ramabam", "vidyarthi", "Agent", "Rudhurudu", "Shaakuntalam", "Dasara", "Das ka Dhamki", "Khosty", "Thugs", "sir", "Amigos", "popcorn", "Michael", "Hunt", "Driver jamuna", "pushpa", "RRR", "Major", "sita ram", "Bhahubali"};
    static String englishMovies[] = {"Gandhi", "Gone girl", "Blood Diamond", "The prestige", "million doller baby", "The sixth sense", "Forest Gump", "The Godfather", "The green mile", "Hotel Rwanda", "Scarface", "The Terminal", "Driving Miss Daisy", "chinatown", "Millions", "The Departed", "Babel", "Traffic", "Titanic", "Gladiator", "Crash", "Superbad", "American Beauty", "Atonement", "munich"};
    static String malayalamMovies[] = {"with Fire As witness", "Vidheyan", "Rat-trap", "Vaishali", "vanaprastham", "season", "Paithrukam", "Innale", "Naalu Pennungal", "Padheyam", "venkalam", "kammatti paadam", "santhqanam", "Vatsalyam", "Sargam", "Ozhimuri", "Pavithram", "Devasuram", "Chenkol", "Arike", "kireedam", "Manjadikuru", "Amen", "Artist", "Thira"};
    public static void main(String moviess[]){
	System.out.println("List of Movies are:");
	System.out.println(kannadaMovies[0] + " " + kannadaMovies[1] + " " + kannadaMovies[2] + " " + kannadaMovies[3] + " " + kannadaMovies[4] + " " + kannadaMovies[5] + " " + kannadaMovies[6] + " " + kannadaMovies[7] + " " + kannadaMovies[8] + " " + kannadaMovies[9] + " " + kannadaMovies[10] + " " + kannadaMovies[11] + " " + kannadaMovies[12] + " " + kannadaMovies[13] + " " + kannadaMovies[14] + " " + kannadaMovies[15] + " " + kannadaMovies[16] + " " + kannadaMovies[17]+ " " + kannadaMovies[18] + " " + kannadaMovies[19] + " " + kannadaMovies[20] + " " + kannadaMovies[21] + " " + kannadaMovies[22] + " " + kannadaMovies[23] + " " + kannadaMovies[24]); 
	System.out.println(hindiMovies[0] + " " + hindiMovies[1] + " " + hindiMovies[2] + " " + hindiMovies[3] + " " + hindiMovies[4] + " " + hindiMovies[5] + " " + hindiMovies[6] + " " + hindiMovies[7] + " " + hindiMovies[8] + " " + hindiMovies[9] + " " + hindiMovies[10] + " " + hindiMovies[11] + " " + hindiMovies[12] + " " + hindiMovies[13] + " " + hindiMovies[14] + " " + hindiMovies[15] + " " + hindiMovies[16] + " " + hindiMovies[17] + " " + hindiMovies[18] + " " + hindiMovies[19] + " " + hindiMovies[20] + " " + hindiMovies[21] + " " + hindiMovies[22] + " " + hindiMovies[23] + " " + hindiMovies[24]);
	System.out.println(telguMovies[0] + " " + telguMovies[1] + " " + telguMovies[2] + " " + telguMovies[3] + " " + telguMovies[4] + " " + telguMovies[5] + " " + telguMovies[6] + " " + telguMovies[7] + " " + telguMovies[8] + " " + telguMovies[9] + " " + telguMovies[10] + " " + telguMovies[11] + " " + telguMovies[12] + " " + telguMovies[13] + " " + telguMovies[14] + " " + telguMovies[15] + " " + telguMovies[16] + " " + telguMovies[17] + " " + telguMovies[18] + " " + telguMovies[19] + " " + telguMovies[20] + " " + telguMovies[21] + " " + telguMovies[22] + " " + telguMovies[23] + " " + telguMovies[24]);
	System.out.println(englishMovies[0] + " " + englishMovies[1] + " " + englishMovies[2] + " " + englishMovies[3] + " " + englishMovies[4] + " " + englishMovies[5] + " " + englishMovies[6] + " " + englishMovies[7]+ " " + englishMovies[8] + " " + englishMovies[9] + " " + englishMovies[10] + " " + englishMovies[11] + " " + englishMovies[12] + " " + englishMovies[13] + " " + englishMovies[14] + " " + englishMovies[15] + " " + englishMovies[16] + " " + englishMovies[17] + " " + englishMovies[18] + " " + englishMovies[19] + " " + englishMovies[20] + " " + englishMovies[21] + " " + englishMovies[22] + " " + englishMovies[23] + " " + englishMovies[24]); 
	System.out.println(malayalamMovies[0] + " " + malayalamMovies[1] + " " + malayalamMovies[2] + " " + malayalamMovies[3] + " " + malayalamMovies[4] + " " + malayalamMovies[5] + " " + malayalamMovies[6] + " " + malayalamMovies[7] + " " + malayalamMovies[8] + " " + malayalamMovies[9] + " " + malayalamMovies[10] + " " + malayalamMovies[11] + " " + malayalamMovies[12] + " " + malayalamMovies[13] + " " + malayalamMovies[14] + " " + malayalamMovies[15] + " " + malayalamMovies[16] + " " + malayalamMovies[17] + " " + malayalamMovies[18] + " " + malayalamMovies[19] + " " + malayalamMovies[20] + " " + malayalamMovies[21] + " " + malayalamMovies[22] + " " + malayalamMovies[23] + " " + malayalamMovies[24]);
	}











}